spring:
  application:
    name: LojaCarrosApp
  datasource:
    url: jdbc:mysql://${DB_HOST}/crud_car?serverTimezone=America/Sao_Paulo&createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo