version: '3.8'

volumes:
  mysqldb_vol:

networks:
  default:
    external:
      name: spring-cloud-network

services:

  app_database:
    container_name: app_database
    image: mysql:8.0.28
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=crud_car
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - mysqldb_vol:/var/lib/mysql

  app_server:
    container_name: app_server
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PROFILE=prod
      - DB_USER=admin
      - DB_PORT=3306
      - DB_PASS=admin
      - DB_HOST=app_database
      - ADDITIONAL_OPTS=-Djava.security.egd -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5555
    ports:
      - '8888:8080'
      - '5555:5555'
    links:
      - app_database
    depends_on:
      - app_database